#!/bin/bash

# URL Shortener - Deploy Script for Ubuntu 22.04
# Автоматический скрипт для деплоя приложения

set -e  # Остановка при ошибке

echo "🚀 Начинаем деплой URL Shortener..."

# Цвета для вывода
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Проверка наличия sudo прав
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}❌ Запустите скрипт с sudo: sudo bash deploy.sh${NC}"
    exit 1
fi

# Функция для вывода успешного сообщения
success() {
    echo -e "${GREEN}✓ $1${NC}"
}

# Функция для вывода предупреждения
warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

# Функция для вывода ошибки
error() {
    echo -e "${RED}❌ $1${NC}"
}

# 1. Обновление системы
echo ""
echo "📦 Шаг 1: Обновление системы..."
apt update && apt upgrade -y
success "Система обновлена"

# 2. Установка необходимых пакетов
echo ""
echo "📦 Шаг 2: Установка необходимых пакетов..."
apt install -y curl git nginx certbot python3-certbot-nginx ufw build-essential
success "Пакеты установлены"

# 3. Настройка файрвола
echo ""
echo "🔥 Шаг 3: Настройка файрвола..."
ufw --force enable
ufw allow 22/tcp   # SSH
ufw allow 80/tcp   # HTTP
ufw allow 443/tcp  # HTTPS
ufw reload
success "Файрвол настроен"

# 4. Установка Node.js
echo ""
echo "📦 Шаг 4: Установка Node.js 20.x..."
if ! command -v node &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt install -y nodejs
    success "Node.js установлен: $(node --version)"
else
    success "Node.js уже установлен: $(node --version)"
fi

# 5. Установка Supabase CLI
echo ""
echo "📦 Шаг 5: Установка Supabase CLI..."
if ! command -v supabase &> /dev/null; then
    npm install -g supabase
    success "Supabase CLI установлен"
else
    success "Supabase CLI уже установлен"
fi

# 6. Создание директории проекта
echo ""
echo "📁 Шаг 6: Создание директории проекта..."
PROJECT_DIR="/var/www/url-shortener"
if [ ! -d "$PROJECT_DIR" ]; then
    mkdir -p "$PROJECT_DIR"
    success "Директория $PROJECT_DIR создана"
else
    success "Директория $PROJECT_DIR уже существует"
fi

# 7. Запрос данных для Supabase
echo ""
echo "🔑 Шаг 7: Настройка Supabase..."
echo "Введите данные вашего Supabase проекта:"
read -p "Project ID (например, cvpooflivzguaaxgkbzz): " SUPABASE_PROJECT_ID
read -p "Anon Key: " SUPABASE_ANON_KEY
read -p "Service Role Key: " SUPABASE_SERVICE_ROLE_KEY

# 8. Запрос домена
echo ""
echo "🌐 Шаг 8: Настройка домена..."
read -p "Введите ваш домен (например, shorturl.com): " DOMAIN

# 9. Копирование файлов проекта
echo ""
echo "📋 Шаг 9: Копирование файлов..."
warning "Убедитесь, что файлы проекта находятся в текущей директории"
read -p "Путь к исходным файлам проекта (текущая директория: $(pwd)): " SOURCE_DIR
SOURCE_DIR=${SOURCE_DIR:-$(pwd)}

if [ -d "$SOURCE_DIR" ]; then
    cp -r "$SOURCE_DIR"/* "$PROJECT_DIR/"
    success "Файлы скопированы в $PROJECT_DIR"
else
    error "Директория $SOURCE_DIR не найдена"
    exit 1
fi

# 10. Обновление конфигурации Supabase
echo ""
echo "⚙️ Шаг 10: Обновление конфигурации..."
cd "$PROJECT_DIR"

# Обновляем utils/supabase/info.tsx
cat > utils/supabase/info.tsx <<EOF
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "$SUPABASE_PROJECT_ID"
export const publicAnonKey = "$SUPABASE_ANON_KEY"
EOF

success "Конфигурация обновлена"

# 11. Установка зависимостей
echo ""
echo "📦 Шаг 11: Установка зависимостей npm..."
cd "$PROJECT_DIR"
npm install
success "Зависимости установлены"

# 12. Сборка проекта
echo ""
echo "🔨 Шаг 12: Сборка production версии..."
npm run build
success "Проект собран"

# 13. Настройка Nginx
echo ""
echo "🌐 Шаг 13: Настройка Nginx..."
cat > /etc/nginx/sites-available/url-shortener <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN www.$DOMAIN;

    root /var/www/url-shortener/dist;
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml+rss image/svg+xml;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    access_log /var/log/nginx/url-shortener-access.log;
    error_log /var/log/nginx/url-shortener-error.log;

    location ~ /\. {
        deny all;
    }
}
EOF

# Создание симлинка
ln -sf /etc/nginx/sites-available/url-shortener /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Проверка конфигурации
nginx -t
systemctl restart nginx

success "Nginx настроен и перезапущен"

# 14. Настройка SSL с Let's Encrypt
echo ""
echo "🔒 Шаг 14: Настройка SSL сертификата..."
read -p "Введите ваш email для уведомлений Let's Encrypt: " EMAIL

certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos -m "$EMAIL"

if [ $? -eq 0 ]; then
    success "SSL сертификат установлен"
else
    warning "Не удалось установить SSL сертификат. Проверьте настройки DNS для домена $DOMAIN"
fi

# 15. Деплой Supabase Functions
echo ""
echo "🚀 Шаг 15: Деплой Supabase Edge Functions..."
cd "$PROJECT_DIR"

# Авторизация в Supabase
warning "Откроется браузер для авторизации в Supabase..."
supabase login

# Линковка проекта
supabase link --project-ref "$SUPABASE_PROJECT_ID"

# Деплой функций
if [ -d "supabase/functions/server" ]; then
    supabase functions deploy server
    
    # Установка секретов
    supabase secrets set SUPABASE_URL="https://$SUPABASE_PROJECT_ID.supabase.co"
    supabase secrets set SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY"
    supabase secrets set SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"
    
    success "Edge Functions задеплоены"
else
    warning "Директория supabase/functions/server не найдена, пропускаем деплой функций"
fi

# Финальные проверки
echo ""
echo "✅ Проверка деплоя..."
sleep 3

HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://$DOMAIN")
if [ "$HTTP_STATUS" -eq 200 ] || [ "$HTTP_STATUS" -eq 301 ] || [ "$HTTP_STATUS" -eq 302 ]; then
    success "Сайт доступен: http://$DOMAIN"
else
    warning "Сайт может быть недоступен. HTTP статус: $HTTP_STATUS"
fi

# Итоговое сообщение
echo ""
echo "════════════════════════════════════════════════════════"
echo -e "${GREEN}🎉 ДЕПЛОЙ ЗАВЕРШЕН УСПЕШНО!${NC}"
echo "════════════════════════════════════════════════════════"
echo ""
echo "📋 Информация о деплое:"
echo "   • URL: https://$DOMAIN"
echo "   • Директория: $PROJECT_DIR"
echo "   • Логи Nginx:"
echo "     - Access: /var/log/nginx/url-shortener-access.log"
echo "     - Error: /var/log/nginx/url-shortener-error.log"
echo "   • Supabase Project: $SUPABASE_PROJECT_ID"
echo ""
echo "📝 Следующие шаги:"
echo "   1. Настройте OAuth провайдеры в Supabase Dashboard"
echo "   2. Создайте админ пользователя через Supabase"
echo "   3. Протестируйте создание коротких ссылок"
echo ""
echo "📚 Документация: $PROJECT_DIR/DEPLOYMENT.md"
echo "════════════════════════════════════════════════════════"
