#!/bin/bash

# URL Shortener - Быстрая установка на Ubuntu 22.04
# Использование: bash quick-deploy.sh

set -e  # Остановка при ошибке

echo "🚀 URL Shortener - Быстрая установка на порт 3000"
echo ""

# Цвета
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

success() { echo -e "${GREEN}✓ $1${NC}"; }
warning() { echo -e "${YELLOW}⚠ $1${NC}"; }
error() { echo -e "${RED}❌ $1${NC}"; }
info() { echo -e "${BLUE}ℹ $1${NC}"; }

# Проверка Node.js
echo "📦 Шаг 1: Проверка Node.js..."
if ! command -v node &> /dev/null; then
    warning "Node.js не установлен. Устанавливаем..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt install -y nodejs
    success "Node.js установлен: $(node --version)"
else
    success "Node.js найден: $(node --version)"
fi

echo ""
echo "📂 Шаг 2: Создание директории проекта..."
PROJECT_DIR="$HOME/url-shortener"
mkdir -p "$PROJECT_DIR"
success "Директория создана: $PROJECT_DIR"

echo ""
info "📋 Скопируйте файлы проекта в: $PROJECT_DIR"
read -p "Нажмите Enter, когда файлы будут скопированы..."

echo ""
echo "🔑 Шаг 3: Настройка Supabase..."
echo "Получите данные из: https://app.supabase.com → Settings → API"
echo ""
read -p "Project ID (без https:// и .supabase.co): " SUPABASE_PROJECT_ID
read -p "Anon Key: " SUPABASE_ANON_KEY

echo ""
info "Обновляем конфигурацию..."
cat > "$PROJECT_DIR/utils/supabase/info.tsx" <<EOF
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "$SUPABASE_PROJECT_ID"
export const publicAnonKey = "$SUPABASE_ANON_KEY"
EOF
success "Конфигурация обновлена"

echo ""
echo "📦 Шаг 4: Установка зависимостей..."
cd "$PROJECT_DIR"
npm install
success "Зависимости установлены"

echo ""
echo "🔨 Шаг 5: Сборка проекта..."
npm run build
success "Проект собран"

echo ""
echo "🚀 Шаг 6: Установка PM2 для управления процессом..."
if ! command -v pm2 &> /dev/null; then
    sudo npm install -g pm2
    success "PM2 установлен"
else
    success "PM2 уже установлен"
fi

echo ""
echo "🎯 Шаг 7: Запуск приложения на порту 3000..."
pm2 start npm --name "url-shortener" -- run preview -- --host 0.0.0.0 --port 3000

# Настройка автозапуска
pm2 startup > /tmp/pm2-startup.sh 2>&1
if grep -q "sudo" /tmp/pm2-startup.sh; then
    info "Требуется sudo для настройки автозапуска"
    grep "sudo" /tmp/pm2-startup.sh | tail -1 | bash
fi
pm2 save

success "Приложение запущено на порту 3000"

echo ""
echo "🔥 Шаг 8: Проверка файрвола..."
if command -v ufw &> /dev/null; then
    sudo ufw allow 3000/tcp 2>/dev/null && success "Порт 3000 открыт в UFW" || warning "UFW не активен"
else
    info "UFW не установлен, пропускаем"
fi

echo ""
echo "════════════════════════════════════════════════════════"
echo -e "${GREEN}🎉 УСТАНОВКА ЗАВЕРШЕНА!${NC}"
echo "════════════════════════════════════════════════════════"
echo ""
echo "📋 Информация:"
echo "   • Директория: $PROJECT_DIR"
echo "   • Порт: 3000"
echo "   • Статус: pm2 status"
echo "   • Логи: pm2 logs url-shortener"
echo ""
echo "🌐 Откройте в браузере:"
# Получаем IP адрес
IP=$(hostname -I | awk '{print $1}')
echo -e "   ${BLUE}http://$IP:3000${NC}"
echo ""
echo "📝 Следующие шаги:"
echo "   1. Настройте базу данных в Supabase"
echo "      См. /SERVER_DEPLOYMENT.md, Шаг 10"
echo "   2. Создайте таблицы через SQL Editor"
echo "   3. Включите Email аутентификацию"
echo "   4. Создайте админ пользователя"
echo ""
echo "📚 Документация: $PROJECT_DIR/SERVER_DEPLOYMENT.md"
echo ""
echo "⚡ Полезные команды PM2:"
echo "   pm2 status              - статус приложений"
echo "   pm2 logs url-shortener  - просмотр логов"
echo "   pm2 restart url-shortener - перезапуск"
echo "   pm2 stop url-shortener    - остановка"
echo ""
echo "════════════════════════════════════════════════════════"
